// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB76jFsFLgKvDeO20YdlXAAIQC7kijQs28',
    appId: '1:77861967352:web:df9530ebf4a8259696320d',
    messagingSenderId: '77861967352',
    projectId: 'scholar-chat-9682e',
    authDomain: 'scholar-chat-9682e.firebaseapp.com',
    storageBucket: 'scholar-chat-9682e.appspot.com',
    measurementId: 'G-5KMCNL4LK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSE-Qc8kjIqD899eKrUIcAdBLAUNCDFrM',
    appId: '1:77861967352:android:56b6f466ce5e055096320d',
    messagingSenderId: '77861967352',
    projectId: 'scholar-chat-9682e',
    storageBucket: 'scholar-chat-9682e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4dZQI674Y-0gGQIm4vJ-1An3W7WoJ-c',
    appId: '1:77861967352:ios:3445b4c0800ec56396320d',
    messagingSenderId: '77861967352',
    projectId: 'scholar-chat-9682e',
    storageBucket: 'scholar-chat-9682e.appspot.com',
    iosClientId: '77861967352-ov1b2pgvt8r8fj3v14slspm3v48gjv58.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe4dZQI674Y-0gGQIm4vJ-1An3W7WoJ-c',
    appId: '1:77861967352:ios:3445b4c0800ec56396320d',
    messagingSenderId: '77861967352',
    projectId: 'scholar-chat-9682e',
    storageBucket: 'scholar-chat-9682e.appspot.com',
    iosClientId: '77861967352-ov1b2pgvt8r8fj3v14slspm3v48gjv58.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChatFirebase',
  );
}
